window.addEventListener("load",function(){var theCanvas=document.getElementById('canvas1');if(theCanvas&&theCanvas.getContext){theCanvas.width=window.innerWidth;theCanvas.height=window.innerHeight;var ctx=theCanvas.getContext("2d");if(ctx){let stars_array=[];stars_array.push(new shooting_star());stars_array.push(new shooting_star());stars_array.push(new shooting_star());stars_array.push(new shooting_star());stars_array.push(new shooting_star());function shooting_star(){this.star_start_x=Math.random()*theCanvas.width;this.star_start_y=Math.random()*theCanvas.height;this.star_size=(Math.random()*3)+1;this.star_end_x=this.star_start_x+(Math.random()*100)+25;this.star_end_y=this.star_start_y-(Math.random()*50)+15}
function draw(star){var gradient=ctx.createLinearGradient(star.star_start_x,star.star_start_y,star.star_end_x,star.star_end_y);gradient.addColorStop("0","rgba(125, 220, 255, 1)");gradient.addColorStop("0.5","rgba(150, 220, 255, 1)");gradient.addColorStop("1.0","rgba(125, 220, 255, 0)");ctx.beginPath();ctx.moveTo(star.star_start_x,star.star_start_y);ctx.lineTo(star.star_end_x,star.star_end_y);ctx.strokeStyle=gradient;ctx.lineWidth=star.star_size;ctx.stroke();ctx.beginPath();ctx.arc(star.star_start_x,star.star_start_y,star.star_size,0,2*Math.PI);ctx.strokeStyle="rgba(125, 220, 255, .20)";ctx.fillStyle="white";ctx.stroke();ctx.fill()}
function update(star){stars_array.forEach(function(star){let x=1;let y=1;let diff_y=Math.abs(star.star_start_y-star.star_end_y);let diff_x=Math.abs(star.star_start_x-star.star_end_x);if(diff_x<0){diff_x=diff_x*diff_x}
if(diff_y<0){diff_y=diff_y*diff_y}
if(star.star_start_x>star.star_end_x){x=(diff_x/70)}else{x=(-diff_x/70)}
if(star.star_start_y<star.star_end_y){y=(-diff_y/80)}else{y=(diff_y/80)}
star.star_start_x=star.star_start_x+x;star.star_start_y=star.star_start_y+y;star.star_end_x=star.star_end_x+x;star.star_end_y=star.star_end_y+y;if(star.star_end_x<0||star.star_end_y<0||star.star_end_x>window.innerWidth||star.star_end_y>window.innerHeight){star.star_start_x=Math.random()*theCanvas.width;star.star_start_y=Math.random()*theCanvas.height;star.star_size=(Math.random()*3)+1;star.star_end_x=star.star_start_x+(Math.random()*100)+25;star.star_end_y=star.star_start_y-(Math.random()*50)+15}})}
function animate(){requestAnimationFrame(animate)
ctx.clearRect(0,0,theCanvas.width,theCanvas.height);stars_array.forEach(function(star){draw(star);update(star)})}
animate()}}})
